# Esercizio 1

Si consideri il dataset delle precipitazioni mensili (mm) nei sette anni dal 2009 al 2015, che ha il seguente formato: 13 record di campi separati da tabulazione di cui il primo è il record di intestazione degli anni (composto da 7 campi) e gli altri 12 sono i record delle piogge mensili (un record per ciascun mese) composti da 8 campi di cui il primo è il nome del mese e i rimanenti 7 sono le piogge mensili lungo gli anni.

Si richiede di predisporre un notebook che permetta di calcolare:

- le precipitazioni medie mensili 
- le precipitazioni totali annue 
- per ognuno degli anni considerati, il numero di mesi con pioggia oltre la soglia S

---

Parametri di input:
- dataset delle precipitazioni
- soglia S

---

Requisiti:
- il notebook deve funzionare anche per un dataset che contiene le rilevazioni per un numero di anni diverso da 7

- definire la funzione `compute_mean()` che prenda in input una lista di numeri e produca in output il valore medio

- definire la funzione `count_elements_greater_than()` che prenda in input una lista di numeri e un valore di soglia e produca in output il numero di valori che superano tale soglia

---

Come produrre l'output?

- produrre le piogge medie mensili in una lista di 12 tuple di dimensione 2 in cui il primo elemento (stringa) sono le prime tre lettere del nome del mese in maiuscolo e il secondo elemento (decimale) è il suo valore medio di pioggia.

- produrre le piogge totali annue in una lista di N (sarà N=7 per questo dataset) tuple di dimensione 2 in cui il primo elemento (stringa) è l'anno e il secondo elemento (intero) è il suo valore totale di pioggia.

- produrre per ogni anno il numero di mesi con pioggia oltre la soglia P in una lista di N tuple di dimensione 2 in cui il primo elemento (stringa) è l'anno e il secondo elemento (intero) il numero di mesi con almeno S mm di pioggia

---

## Cosa serve per svolgere l'esercizio?

### 1) Leggere le righe di un file

Lo statement:

    with open(input_file_name, ’r’) as input_file:
        file_rows = input_file.readlines()
        
permette di aprire l'*handle* in lettura `input_file` al file che ha nome `input_file_name` e di ottenere poi la lista `file_rows` delle sue righe (oggetti di tipo `str`).

Al termine di esecuzione dello statement, l'*handle* `input_file` viene chiuso e lo script può proseguire e processare la lista `file_rows`.

Ci si deve ricordare che prima di processare le righe del file è opportuno rimuovere eventuali caratteri di spazio finali.

Il metodo `rstrip()` degli oggetti di tipo `str` restituisce una copia della stringa invocante dopo avere rimosso il più lungo suffisso contenente solo caratteri appartenenti alla stringa passata come argomento.

Se l’argomento viene omesso, allora il metodo rimuove tutti i caratteri di tipo spazio (tabulazione, *newline*, etc.)

In [62]:
'aaaa \n  '.rstrip()

'aaaa'

In [63]:
'aaaa \n  '.rstrip(' ')

'aaaa \n'

### 2) Costruire una matrice

Una matrice può essere implementata in Python come una lista di liste della stessa dimensione. Ad esempio, la seguente è una matrice di 3 righe e 4 colonne

In [2]:
lista = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
lista

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

Python permette di trasformarla in un oggetto di tipo `ndarray`. 

La classe `ndarray` è definita nel modulo `numpy`, che mette a disposizione anche la funzione `array()` per trasformare una lista di liste in un oggetto `ndarray` e le funzioni per eseguire le tipiche operazioni su matrici.

In [8]:
import numpy as np
matrice = np.array(lista)
matrice

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Si può usare la stessa sintassi di accesso delle liste.

In [73]:
matrice[0]

array([1, 2, 3, 4])

In [74]:
matrice[0][2]

3

La scansione delle righe avviene con ciclo for.

In [70]:
for row in matrice:
    print(row)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


La funzione `len()` restituisce il numero di righe della matrice.

In [10]:
len(matrice)

3

La funzione `transpose()` di `numpy` permette di ottenere la trasposta di una matrice.

In [11]:
matrice_t = np.transpose(matrice)
matrice_t

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Il metodo `transpose()` degli oggetti `ndarray` permette di ottenere la trasposta della matrice invocante.

In [12]:
matrice_t = matrice.transpose()
matrice_t

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

### 3) Convertire una lista di stringhe in lista di interi

La funzione `map()` prende il nome di una funzione come primo argomento e un oggetto iterabile come secondo argomento e restituisce un oggetto che mappa ognuno degli elementi del secondo argomento secondo la funzione specificata come primo argomento e che può essere convertito in un oggetto di tipo lista.

In [69]:
lista = ['1', '2', '3']
list(map(int, lista))

[1, 2, 3]

### 4) Convertire in decimale un valore intero

La funzione `float()` converte in decimale il valore passato come argomento.

In [66]:
float(13)

13.0

### 5) Sommare i valori presenti in una lista o in una tupla

La funzione `sum()` restituisce la somma dei valori della lista o della tupla passata come argomento.

In [21]:
sum([1, 2, 3, 4, 5])

15

### 6) Trasformare una stringa in caratteri maiuscoli

Il metodo `upper()` degli oggetti di tipo `str` restituisce una copia in maiuscolo della stringa invocante

In [24]:
'ciao'.upper()

'CIAO'

### 7) Separare una stringa attraverso un separatore

Il metodo `split()` degli oggetti di tipo `str` restituisce la lista degli elementi ottenuti separando la stringa invocante tramite il separatore passato come argomento.

Se l’argomento viene omesso la stringa invocante viene separata usando spazi di qualsiasi tipo.

In [33]:
'aa\taa\taa'.split()

['aa', 'aa', 'aa']

In [34]:
'aa \n\t aa \n\t   aa'.split()

['aa', 'aa', 'aa']

In [35]:
'aa \n\t aa \n\t   aa'.split(' ')

['aa', '\n\t', 'aa', '\n\t', '', '', 'aa']

In [64]:
'aa\t\taa\taa'.split('\t')

['aa', '', 'aa', 'aa']

### 8) Rimuovere da una lista l'elemento in una certa posizione

Il metodo `pop()` degli oggetti di tipo `list` rimuove e restituisce l’elemento della lista invocante che si trova nella posizione specificata come argomento.

In [48]:
lista = [1,2,3,4]
element = lista.pop(1)
element

2

In [49]:
lista

[1, 3, 4]

### 9) Contare gli elementi di una sequenza che sono uguali a un certo valore

Il metodo `count()` delle *sequenze* restituisce il numero di elementi della *sequenza* invocante che sono uguali al valore passato come argomento

In [51]:
[True,False,True,True].count(True)

3

In [52]:
'aabbabbbba'.count('a')

4

### 10) Unire due liste di dimensione N in una lista di dimensione N i cui elementi sono tuple di dimensione due che uniscono gli elementi nelle stesse posizioni delle due liste.

La funzione `zip()` prende in input una serie di oggetti iterabili della stessa dimensione e restituisce un oggetto che unisce in tuple tutti gli elementi nella stessa posizione.

In [1]:
list(zip([1,2,3], [3,4,5]))