# Esercizio 7

Prendere in input un file in formato `FASTQ` e determinare:

- la distribuzione della qualità media per read
- la distribuzione della qualità media per posizione
- la distribuzione delle basi A, C, G e T per posizione

Eseguire inoltre il *trimming* dei reads scegliendo una soglia minima di qualità, sulla base dei risultati ottenuti sopra e scartare i reads che risultano troppo corti.

---

## Dataset in input

In [17]:
fastq_file_name = './SRR18961685-5000.fastq'

## Definizione della funzione `ascii_to_quality()`

La funzione prende come argomento un carattere e restituisce il valore di qualità codificato secondo la seguente funzione:

    C = ASCII(min(93,Q)+33)

In [19]:
def ascii_to_quality(c):
    return ord(c)-33

## Lettura del dataset `FASTQ`

a) Leggere il file `FASTQ` in input.

In [20]:
with open(fastq_file_name, 'r') as fastq_input_file:
    input_file_rows = [row.rstrip() for row in fastq_input_file.readlines()]

In [21]:
input_file_rows

['@SRR18961685.1 1 length=152',
 'TTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGTTTAGGGTTAGGGTTACGGATAGGGTAACGTGTAGCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCATAACCCTAACCCAA',
 '+SRR18961685.1 1 length=152',
 '@A?ACDBECEEECECEEECECEE>@@CEEECEC?EEC?CEE//EC0EE//:0E.//C-@=+D:0..C)D-?///:1@@@>ABCCDBCDDDECDDDDDCDDDDECDDDDECDDDDECD<D,DCDD+DEC,;D,6CD<,*.C,-:,BC,-@-,@',
 '@SRR18961685.2 2 length=152',
 'CCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAGGGTTAGGGTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGT',
 '+SRR18961685.2 2 length=152',
 '@@@AACCDDECDDDDECDDDDECDDDDECDDDDECDDDDECDDDDACDDDDECDDD9BCDDDD6CD-DDABB@,@7@A@@@CBDDDBCEEECECEEDCECEEECECEE<CECEEE??CEEDCE9EEECECEEE/ECE=E/EC@EEC/AAAA0',
 '@SRR18961685.3 3 length=152',
 'GGGTTAGGGTTAGGGTTGGGGTTAGGGGTTAGGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGGTTAGGCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAACCCTAA',
 '+SRR18961685.3 3 length=152',
 '@AA?CBDEEC2CEEECEFEEE

b) Raggruppare i *record* a gruppi di quattro (cioé per read in formato `FASTQ`).

In [23]:
fastq_read_list = [input_file_rows[i:i+4] for i in range(0, len(input_file_rows), 4)]

In [3]:
#fastq_read_list

c) Recuperare il numero di reads e la loro lunghezza (supposta costante).

In [143]:
read_length

152

In [145]:
number_of_reads

5000

## Determinare la distribuzione della qualità media per read

a) Creare la matrice dei valori di qualità dei reads, in modo tale che l'i-esima riga contenga le qualità delle basi dell'i-esimo read.

In [27]:
import numpy as np

In [29]:
qualities_per_read = np.array([list(map(ascii_to_quality, list(read[3]))) for read in fastq_read_list])

In [30]:
qualities_per_read

array([[31, 32, 30, ..., 12, 11, 31],
       [31, 31, 31, ..., 32, 32, 15],
       [31, 32, 32, ..., 32, 30, 31],
       ...,
       [31, 32, 32, ..., 31, 32, 31],
       [31, 32, 33, ..., 32, 32, 31],
       [31, 31, 31, ..., 32, 32, 31]])

b) Ottenere la lista delle qualità medie dei reads, arrotondate all'intero più vicino.

In [4]:
#mean_quality_per_read

c) Determinare la distribuzione delle frequenze assolute delle qualità medie dei reads.

In [157]:
unique_values

array([24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35])

In [24]:
counts

array([   1,    1,    2,    7,   17,   23,   27,   29,   59,   97,  710,
       4027])

d) Disegnare il diagramma a barre delle frequenze assolute.

## Determinare la distribuzione della qualità media per posizione

a) Ottenere la matrice delle qualità per posizione, in modo tale che l'i-esima riga contenga le qualità dell'i-esima base dei reads.

In [30]:
qualities_per_pos

array([[31, 31, 31, ..., 31, 31, 31],
       [32, 31, 32, ..., 32, 32, 31],
       [30, 31, 32, ..., 32, 33, 31],
       ...,
       [12, 32, 32, ..., 31, 32, 32],
       [11, 32, 30, ..., 32, 32, 32],
       [31, 15, 31, ..., 31, 31, 31]])

b) Ottenere la lista delle qualità medie per posizione, arrotondate all'intero più vicino.

In [5]:
#mean_quality_per_pos

c) Disegnare il diagramma delle qualità medie per posizione.

## Determinare la distribuzione delle basi `A`, `C`, `G`, `T` per posizione

a) Creare la matrice delle basi dei reads, in modo tale che l'i-esima riga contenga le i-esime basi dei reads.

In [174]:
bases_per_pos

array([['T', 'C', 'G', ..., 'C', 'T', 'A'],
       ['T', 'C', 'G', ..., 'T', 'T', 'C'],
       ['A', 'C', 'G', ..., 'T', 'G', 'C'],
       ...,
       ['C', 'G', 'T', ..., 'A', 'G', 'G'],
       ['A', 'G', 'A', ..., 'G', 'G', 'G'],
       ['A', 'T', 'A', ..., 'A', 'A', 'A']], dtype='<U1')

b) Per ogni posizione, ottenere la distribuzione delle frequenze assolute delle basi.

In [6]:
#count_list

c) Per ogni posizione, ottenere la distribuzione delle frequenze relative delle basi.

In [7]:
#frequency_list

d) Per ogni posizione, disegnare il diagramma a barre della distribuzione delle basi.

## Eseguire il *trimming* dei reads

a) Scegliere una soglia minima di qualità.

In [46]:
min_quality = 20

**b) Definire una funzione che prenda come argomento una stringa di qualità e una soglia minima e restituisca l'intervallo di *trimming* (cioé, il più lungo intervallo di posizioni contenente solo caratteri che codificano una qualità almeno uguale alla soglia minima).**

---
**SPIEGAZIONE**

Stringa di qualità di prova.

In [183]:
quality_string = '@A?ACDBECEEECECEEECECEE>@@CEEECEC?EEC?CEE//EC0EE//:0E.//C-@=+D:0..C)D-?///:1@@@>ABCCDBCDDDECDDDDDCDDDDECDDDDECDDDDECD<D,DCDD+DEC,;D,6CD<,*.C,-:,BC,-@-,@'

1) Costruire una lista di valori booleani, in modo tale che l'i-esimo valore è `True` se l'i-esimo carattere codifica una qualità maggiore o uguale alla soglia minima.

**NB**: Le posizioni di inizio e fine della più lunga sottolista di soli valori `True` saranno le posizioni di inizio e fine della sottostringa di read che ha qualità almeno pari alla soglia minima.

In [8]:
#bool_list

2. Determinare la lista delle sole posizioni che contengono un valore `True` preceduto da un valore `False`. La posizione `0` è da intendere preceduta da un valore `False`.

In [9]:
#start_list

3. Aggiungere in testa la posizione di *default* `1`.

In [10]:
#start_list

4. Ottenere la lista delle posizioni che contengono un valore `True` seguito da un valore `False`. L'ultima posizione è da intendere seguita da un valore `False`.

In [11]:
#end_list

5. Aggiungere in testa la posizione di *default* `0`.

In [12]:
#end_list

6. Ottenere la lista delle lunghezze degli intervalli di soli valori `True`.

In [195]:
interval_lengths

[0, 41, 2, 2, 1, 1, 1, 2, 2, 1, 1, 1, 1, 43, 4, 3, 2, 4, 1, 1, 2, 1, 1]

7. Ottenere la posizione che contiene la massima lunghezza.

8. Determinare le posizioni di inizio e fine dell'intervallo di massima lunghezza.

In [200]:
interval_start

76

In [201]:
interval_end

118

`[interval_start, interval_end+1]` è l'intervallo di *trimming*.

**NB**: se viene restituita la lista `[1,1]` allora significa che tutti i valori in `bool_list` sono uguali a `False` (cioé tutte le qualità sono al di sotto della soglia minima), e il *trimming* restituirà la stringa vuota.

---

**c) Definire una funzione che prenda come argomenti una soglia minima di qualità e un read in formato `FASTQ` (lista dei quattro *record* `FASTQ`) e restituisca il read in formato `FASTQ` dopo essere stato sottoposto a *trimming*.**

**d) Effettuare il *trimming* dei reads.**

In [13]:
#fastq_read_list

**e) Eliminare i reads troppo corti.**

In [205]:
min_length = 30

In [14]:
#fastq_read_list

## Determinare la distribuzione delle qualità medie dei reads dopo il *trimming*

a) Ottenere la lista dei valori di qualità dei reads.

In [15]:
#qualities_per_read

b) Ottenere la lista delle qualità medie dei reads, arrotondate all'intero più vicino.

In [16]:
#mean_quality_per_read

c) Determinare la distribuzione delle frequenze assolute delle qualità medie dei reads.

In [237]:
unique_values

array([32, 33, 34, 35])

In [238]:
counts

array([   2,   27,  426, 4459])

d) Disegnare il diagramma a barre